kmpt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('landing.urls')),
    url(r'^', include('recipes.urls')),
    url(r'^', include('search.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


         

landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^recipes/$', views.home, name = 'home'),
	url(r'^$', views.home, name = 'home'),
	url(r'^recipes/new/$', views.new, name = 'new'),
	url(r'^recipes/best/$', views.best, name = 'best'),
	url(r'^recipes/hot/$', views.hot, name = 'hot'),
	url(r'^recipes/archive/$', views.archive, name = 'archive'),
	url(r'^about/$', views.about, name = 'about'),
	url(r'^tags/$', views.tags, name = 'tags'),
]

recipes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from recipes import views
from recipes.models import *

urlpatterns = [
	url(r'^recipes/(?P<recipe_id>\w+)/$', views.recipe, name = 'recipe'),
] 

search/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'search'

urlpatterns = [
	url(r'^search/$', views.ESearchView.as_view(), name = 'index'),
]

landing/models.py
from django.db import models

class visitor(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=128)
    
    def __str__(self):
        return 'Пользователь %s %s' % (self.name, self.email)
    
    class Meta:
        verbose_name = 'visitor'
        verbose_name_plural = 'visitors'
        

    

recipes/models.py
from django.db import models
import datetime

class Recipe(models.Model):
    TAG_CHOICES = (('Горячее блюдо', 'Горячее блюдо'), ('Холодное блюдо', 'Холодное блюдо'), ('Салат', 'Салат'), ('Суп', 'Суп'), ('Выпечка', 'Выпечка'))
    STATUS_CHOICES = (('Свежее', 'Свежее'), ('Популярное', 'Популярное'), ('Лучшее', 'Лучшее'), ('Архив', 'Архив')) 
    
    name = models.CharField(max_length=64, default=None)
    description = models.TextField(default=None, max_length=100, blank=True, null=True)
    ingredients = models.TextField(default=None)
    full_recipe = models.TextField(default=None)
    views_counter = models.IntegerField(default=None, blank=True, null=True)
    tag = models.CharField(max_length=64, choices=TAG_CHOICES, default=None)
    status = models.CharField(max_length=64, choices=STATUS_CHOICES, default=None, blank=True, null=True)
    image = models.ImageField(upload_to='recipes/images/', blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __str__(self):
        return 'Рецепт %s' % self.name
    
    class Meta:
        verbose_name='Рецепт'
        verbose_name_plural='Рецепты'
        

        

search/models.py
from django.db import models

# Create your models here.

landing/forms.py
from django import forms
from .models import *

class VisitorForm(forms.ModelForm):
    
    class Meta:
        model = visitor
        exclude = ['']

landing/views.py
from django.shortcuts import render
from .forms import VisitorForm
from recipes.models import Recipe

def home(request):
	recipes = Recipe.objects.all()
	for recipe in recipes:
		recipe.status = 'Архив'
		recipe.save(update_fields=['status'])
	k = 0
	recipes = Recipe.objects.order_by('-created')
	try:
		for i in range(9):
			recipe_new = recipes[0+k]
			recipe_new.status = 'Свежее'
			recipe_new.save(update_fields=['status'])
			k += 1
		k = 0
		recipes = Recipe.objects.order_by('-views_counter')
		i = 0
		while i < 6:
			recipe_best = recipes[0+k]
			if recipe_best.status != 'Свежее':
				recipe_best.status = 'Лучшее'
				recipe_best.save(update_fields=['status'])
				i += 1
			k += 1
		k = 0

	except IndexError:
		pass
	recipes_new = Recipe.objects.filter(status='Свежее')
	# recipes_hot = Recipe.objects.filter(status='Популярное')
	recipes_best = Recipe.objects.filter(status='Лучшее')
	return render(request, 'landing/home.html', locals())
	
def new(request):
	
	recipes_new = Recipe.objects.filter(status='Свежее')
	return render(request, 'recipes/new.html', locals())

def best(request):
	
	recipes_best = Recipe.objects.filter(status='Лучшее')
	return render(request, 'recipes/best.html', locals())

def archive(request):
	
	recipes_arc = Recipe.objects.filter(status='Архив')
	return render(request, 'recipes/archive.html', locals())

def hot(request):
	
	recipes = Recipe.objects.all()
	recipes_hot = Recipe.objects.filter(status='Популярное')
	return render(request, 'recipes/hot.html', locals())

def about(request):
	return render(request, 'landing/about.html', locals())

def tags(request):
	pokushatz = request.GET.get('pokushatz')
	recipes = Recipe.objects.filter(tag=pokushatz)
	if pokushatz == 'Суп':
		header = 'Супы'
	if pokushatz == 'Салат':
		header = 'Салаты'
	if pokushatz == 'Горячее блюдо':
		header = 'Горячие блюда'
	if pokushatz == 'Холодное блюдо':
		header = 'Холодные блюда'
	if pokushatz == 'Выпечка':
		header = 'Выпечка'
	return render(request, 'landing/pokushatz.html', locals())
	

recipes/views.py
from django.shortcuts import render, get_object_or_404
from recipes.models import *
from django.db.models import Count
from django.http import HttpResponseRedirect

def recipe(request, recipe_id):
    
    recipe = Recipe.objects.get(id=recipe_id)
    # recipes = Recipe.objects.order_by('-views_counter')
    # k = 0
    # while k < 2:
    #     recipe_best = recipes[0+k]
    #     recipe_best.status = 'Лучшее'
    #     recipe_best.save(update_fields=['status'])
    #     k += 1
    # 
    # k = 0
    # recipes = Recipe.objects.order_by('-created')
    # while k < 1:
    #     recipe_new = recipes[0+k]
    #     recipe_best.status = 'Свежее'
    #     recipe_best.save(update_fields=['status'])
    #     k += 1
    if recipe_id not in request.COOKIES:
        recipe.views_counter += 1
        recipe.save(update_fields=['views_counter'])
        response = render(request, 'recipes/recipes.html', locals())
        response.set_cookie(recipe_id, 'already seen')
        return response
        
    return render(request, 'recipes/recipes.html', locals())

search/views.py
# from django.shortcuts import render
# 
# def search(request):
#     
#     return render(request, 'search/search.html', locals())

from django.shortcuts import render_to_response
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views import View

from recipes.models import Recipe


class ESearchView(View):
    template_name = 'search/search.html'

    def get(self, request, *args, **kwargs):
        context = {}

        question = request.GET.get('q')
        question = question.lower()
        
        if question is not None:
            search_recipes = Recipe.objects.filter(name__contains=question[1:])
            context['last_question'] = '?q=%s' % question
            context['recipes_list'] = search_recipes

        return render_to_response(template_name=self.template_name, context=context)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <title>Best recipes ever</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/recipes/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
        <script>
            var smoothJumpUp = function() {
                if (document.body.scrollTop>0 || document.documentElement.scrollTop>0) {
                    window.scrollBy(0,-50);
                    setTimeout(smoothJumpUp, 20);
                }
            };
        </script>
    </head>
    <body>
        <div class='wrapper'>
            <div class='wrapper-content'>
                {% include 'navbar.html' %}
            
                {% block content %}
                {% endblock %}
                
            </div>
        </div>
        {% include 'footer.html' %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <div class='row'>
            <div class='col-9'>
                <a href='{% url "about" %}' id='archive'>
                    <span>О сайте</span>
                </a>
            </div>
            <div class='col-3'>
                <a href='#' id='upbutton' onclick='smoothJumpUp(); return false;'>
                    <span>Наверх</span>
                </a>
            </div>
        </div>
        <div class='row'>
            <div class='col-12'>
                <a href="{% url 'archive' %}" id='archive'>
                    <span>Архив</span>
                </a>
            </div>
        </div>
    </div>
</footer>

templates/landing/about.html
{% extends 'base.html' %}
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>О сайте</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/recipes/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% block content %}
    
    <div class='container'>
        <div class='row'>
            <div class='col-12'>
                <h1 class='text-center'>О сайте</h1>
            </div>
        </div>
        <div class='row'>
            
        </div>
    </div>
    
    {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src='c:\python36\django\scripts\kmpt\static\js\bootstrap.min.js'></script>
  </body>
</html>

templates/landing/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class='section section1'>
        <div class='container'>
            <div class='col-lg-12 header'>
                <h1 class='text-center'>
                    Свежие рецепты
                </h1>
            </div>
            <div class='row justify-content-center'>
                 
                {% for recipe in recipes_new %}
                    <div class='col'>
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="{{ recipe.image.url }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ recipe.name }}</h5>
                                <p class="card-text">{{ recipe.description }}</p>
                                {% if recipe.status %}
                                    <span class='recipe-status new'>{{ recipe.status }}</span>
                                {% endif %}
                                <!--<span class="recipe-tag">{{ recipe.tag }}</span><br>-->
                                <img src='{% static "img/view.svg" %}'>
                                <span class='recipe-views'> {{ recipe.views_counter }} </span><br>
                                <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a> 
                            </div>
                        </div>
                    </div>
                {% endfor %}
                
            </div>
        </div>
    </div>
    <div class='section section2'>
        <div class='container'>
            <div class='col-lg-12 header'>
                <h1 class='text-center'>
                    Лучшие рецепты
                </h1>
            </div>
            <div class='row justify-content-center'>
                 
                {% for recipe in recipes_best %}
                    <div class='col'>
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="{{ recipe.image.url }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ recipe.name }}</h5>
                                <p class="card-text">{{ recipe.description }}</p>
                                {% if recipe.status %}
                                    <span class='recipe-status best'>{{ recipe.status }}</span>
                                {% endif %}
                                <img src='{% static "img/view.svg" %}'>
                                <span class='recipe-views'> {{ recipe.views_counter }} </span><br>
                                <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                
            </div>
        </div>
    </div>
<!--    <div class='section section3'>
        <div class='container'>
            <div class='col-lg-12 header'>
                <h1 class='text-center'>
                    Популярные рецепты
                </h1>
            </div>
            <div class='row'>
                 
                {% for recipe in recipes_hot %}
                    <div class='col'>
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="{{ recipe.image.url }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ recipe.name }}</h5>
                                <p class="card-text">{{ recipe.description }}</p>
                                {% if recipe.status %}
                                    <span class='recipe-status hot'>{{ recipe.status }}</span>
                                {% endif %}
                                <span class="recipe-tag">{{ recipe.tag }}</span><br>
                                <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                
            </div>
        </div>
    </div>-->
{% endblock %}

templates/landing/landing.html
<html>
    <head>
        <meta charset='utf-8'>
        <style>
            .title {
                text-align: center;
                
            }
        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="c:\python363\django\scripts\kmpt\static\css\bootstrap.min.css">
        <link rel="stylesheet" href="c:\python363\django\scripts\kmpt\static\css\style.css">
    </head>
    <body>
        <div class='container'>
            <div class='row'>
                <div class='col-lg-4 col-lg-offset-4'>
                    <h1 class='title'>Введите что-нибудь в форму ниже</h1>
                </div>
                <div>
                    <form action='' method='post'>{% csrf_token %}
                        {{ form.as_p }}
                        <div>
                            <button type='submit'>Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
        <script src='c:\python363\django\scripts\kmpt\static\js\bootstrap.min.js'></script>
    </body>
</html> 
<!--
<html>
        <head>
                <meta charset='utf-8'>
        </head>
        <body>
                <script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
                <script src="https://api-maps.yandex.ru/2.0/?load=package.full&lang=eu-EU" type="text/javascript"></script>
                <script async type="text/javascript">
                        $(document).ready(function(){
                                ymaps.ready(function(){
                                var geolocation = ymaps.geolocation;
                                $('#tow').html('Ваш город: '+geolocation.city);
                                });
                        });
                </script>
                <div id="tow">Ваш город: ... определяется ...</div>
                <p id='temperature'>Температура за бортом: ...определяется...</p>
                <p id ='conditions'>Погодные условия: ...определяется...</p>
        </body>
</html> -->

templates/landing/pokushatz.html
{% extends 'base.html' %}
{% load staticfiles %}

<html lang="en">
  <head>
    <title>Best recipes ever</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/recipes/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% block content %}
        <div class='container'>
            <div class='row'>
                <div class='col-12'>
                    <h1 class='text-center'>{{ header }}</h1>
                </div>
            </div>
            <div class='row justify-content-center'>
                {% if recipes %}
                    {% for recipe in recipes %}
                        <div class='col'>
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="{{ recipe.image.url }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ recipe.name }}</h5>
                                    <p class="card-text">{{ recipe.description }}</p>
                                    {% if recipe.status == 'Свежее' %}
                                        <span class='recipe-status new'>{{ recipe.status }}</span>
                                    {% endif %}
                                    {% if recipe.status == 'Лучшее' %}
                                        <span class='recipe-status best'>{{ recipe.status }}</span>
                                    {% endif %}
                                    {% if recipe.status == 'Архив' %}
                                        <span class='recipe-status archive'>{{ recipe.status }}</span>
                                    {% endif %}
                                    <!--<span class="recipe-tag">{{ recipe.tag }}</span><br>-->
                                    <img src="{% static 'img/view.svg' %}">
                                    <span class='recipe-views'> {{ recipe.views_counter }} </span><br>
                                    <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a> 
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>  
        </div>   
    {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src='c:\python36\django\scripts\kmpt\static\js\bootstrap.min.js'></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="{% url 'home' %}">Бюджетные рецепты</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Домой<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'best' %}">Лучшее</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'new' %}">Свежее</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Все рецепты
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'tags' %}?pokushatz=Суп">Супы</a>
          <a class="dropdown-item" href="{% url 'tags' %}?pokushatz=Салат">Салаты</a>
          <a class="dropdown-item" href="{% url 'tags' %}?pokushatz=Горячее блюдо">Горячие блюда</a>
          <a class="dropdown-item" href="{% url 'tags' %}?pokushatz=Холодное блюдо">Холодные блюда</a>
          <a class="dropdown-item" href="{% url 'tags' %}?pokushatz=Выпечка">Выпечка</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search:index' %}" method="get">
      <input required class="form-control mr-sm-2" type="search" id="search" name="q" placeholder="Поиск" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
    </form>
  </div>
</nav>

templates/recipes/archive.html
{% extends 'base.html' %}
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Best recipes ever</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/recipes/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% block content %}
        <div class='section section1'>
            <div class='container'>
                <div class='col-lg-12 header'>
                    <h1 class='text-center'>
                        Архив
                    </h1>
                </div>
                <div class='col-12'>
                    
                </div>
                <div class='row'>
                 
                    {% for recipe in recipes_arc %}
                        <div class='col'>
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="{{ recipe.image.url }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ recipe.name }}</h5>
                                    <p class="card-text">{{ recipe.description }}</p>
                                    {% if recipe.status %}
                                        <span class='recipe-status archive'>{{ recipe.status }}</span>
                                    {% endif %}
                                    <!--<span class="recipe-tag">{{ recipe.tag }}</span><br>-->
                                    <img src='{% static "img/view.svg" %}'>
                                    <span class='recipe-views'> {{ recipe.views_counter }} </span><br>
                                    <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a> <!--{% url 'recipe' recipe.id %}-->
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                
                </div>
            </div>
        </div>
    {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src='c:\python36\django\scripts\kmpt\static\js\bootstrap.min.js'></script>
  </body>
</html>

templates/recipes/best.html
{% extends 'base.html' %}
{% load staticfiles %}

<html lang="en">
  <head>
    <title>Лучшее</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/recipes/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% block content %}
          <div class='section section1'>
            <div class='container'>
                <div class='col-12 header'>
                    <h1 class='text-center'>
                        Лучшие рецепты
                    </h1>
                </div>
                <div class='row'>
                 
                    {% for recipe in recipes_best %}
                        <div class='col'>
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="{{ recipe.image.url }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ recipe.name }}</h5>
                                    <p class="card-text">{{ recipe.description }}</p>
                                    {% if recipe.status %}
                                        <span class='recipe-status best'>{{ recipe.status }}</span>
                                    {% endif %}
                                    <!--<span class="recipe-tag">{{ recipe.tag }}</span><br>-->
                                    <img src='{% static "img/view.svg" %}'>
                                    <span class='recipe-views'> {{ recipe.views_counter }} </span><br>
                                    <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a> <!--{% url 'recipe' recipe.id %}-->
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                
                </div>
            </div>
          </div>
    {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src='c:\python36\django\scripts\kmpt\static\js\bootstrap.min.js'></script>
  </body>
</html>

templates/recipes/hot.html
{% extends 'base.html' %}
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Best recipes ever</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/recipes/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% block content %}
          <div class='section section1'>
            <div class='container'>
                <div class='col-lg-12 header'>
                    <h1 class='text-center'>
                        Популярные рецепты
                    </h1>
                </div>
                <div class='row'>
                 
                    {% for recipe in recipes_hot %}
                        <div class='col'>
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="{{ recipe.image.url }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ recipe.name }}</h5>
                                    <p class="card-text">{{ recipe.description }}</p>
                                    {% if recipe.status %}
                                        <span class='recipe-status hot'>{{ recipe.status }}</span>
                                    {% endif %}
                                    <span class="recipe-tag">{{ recipe.tag }}</span><br>
                                    <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a> <!--{% url 'recipe' recipe.id %}-->
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                
                </div>
            </div>
          </div>
    {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src='c:\python36\django\scripts\kmpt\static\js\bootstrap.min.js'></script>
  </body>
</html>

templates/recipes/new.html
{% extends 'base.html' %}
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Свежее</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/recipes/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% block content %}
        <div class='section section1'>
            <div class='container'>
                <div class='col-lg-12 header'>
                    <h1 class='text-center'>
                        Свежие рецепты
                    </h1>
                </div>
                <div class='row'>
                 
                    {% for recipe in recipes_new %}
                        <div class='col'>
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="{{ recipe.image.url }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ recipe.name }}</h5>
                                    <p class="card-text">{{ recipe.description }}</p>
                                    {% if recipe.status %}
                                        <span class='recipe-status new'>{{ recipe.status }}</span>
                                    {% endif %}
                                    <!--<span class="recipe-tag">{{ recipe.tag }}</span><br>-->
                                    <img src='{% static "img/view.svg" %}'>
                                    <span class='recipe-views'> {{ recipe.views_counter }} </span><br>
                                    <a href="{% url 'recipe' recipe.id %}" class="btn btn-primary">Просмотреть рецепт</a> <!--{% url 'recipe' recipe.id %}-->
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                
                </div>
            </div>
        </div>
    {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src='c:\python36\django\scripts\kmpt\static\js\bootstrap.min.js'></script>
  </body>
</html>